[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/zellij"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12

[window]
padding.x = 14
padding.y = 14
opacity = 0.95

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "V", mods = "Control", action = "Paste" },
{ key = "C", mods = "Control|Shift", action = "Copy" },
]

[colors]
[colors.primary]
background = '#1b1b1b'
foreground = '#ebdbb2'

[colors.normal]
black = '#282828'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'

[colors.bright]
black = '#928374'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#ebdbb2'

[terminal]
